# Generated by Django 5.1.7 on 2025-04-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Rider', 'Rider'), ('Driver', 'Driver')], max_length=20, unique=True),
        ),
    ]
